Fix problem where getResources method causes NoSuchMethodError on 1.1 JVMs, due to lack of ClassLoader.getResources method. See bugzilla #37484.
git-svn-id: https://svn.apache.org/repos/asf/jakarta/commons/proper/logging/trunk@375866 13f79535-47bb-0310-9956-ffa450edef68