Fix Javadoc (Java 11 on Windows)
[ERROR] C:\Users\ggregory\git\a\commons-logging\src\main\java\org\apache\commons\logging\LogFactory.java:892:
error: header used out of sequence: <H4>
[ERROR]      * <h4>ClassLoader conflicts</h4>
[ERROR]        ^