Ignore tests that set a SecurityManager on Java 21 and up:
Java 21 and up:
java.lang.UnsupportedOperationException: The Security Manager is
deprecated and will be removed in a future release